#!/usr/bin/env python3
"""
skillset_gen.py (SAMPLE)
On-demand skillset emitter:
- reads local .ai/SKILLS/
- optionally reads external skill roots listed in .ai/SKILLS/sources.md (as paths, restricted to specific base)
- emits .ai/SKILLSETS/active_skillset.generated.md

NOTE: This is a SAMPLE. No network. No git ops. No automatic writes unless explicitly instructed.
"""

from __future__ import annotations
from pathlib import Path
import argparse
import re

def repo_root_from_cwd() -> Path:
    p = Path.cwd()
    # naive: walk up until .git or .ai exists
    for _ in range(12):
        if (p / ".git").exists() or (p / ".ai").exists():
            return p
        if p.parent == p:
            break
        p = p.parent
    return Path.cwd()

def parse_external_roots(sources_md: Path, repo_root: Path, external_base: str) -> list[Path]:
    if not sources_md.exists():
        return []
    txt = sources_md.read_text(encoding="utf-8", errors="replace")
    roots = []
    base_dir = (repo_root / external_base).resolve()
    # simple parse: lines like "skill_root: <path>"
    for m in re.finditer(r"skill_root:\s*([^\n]+)", txt):
        raw_path = m.group(1).strip()
        p = Path(raw_path)
        if p.is_absolute():
            continue
        candidate = (repo_root / p).resolve()
        try:
            candidate.relative_to(base_dir)
            roots.append(candidate)
        except ValueError:
            continue
    return roots

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", default=".ai/SKILLSETS/active_skillset.generated.md", help="Target output file")
    ap.add_argument("--sources", default=".ai/SKILLS/sources.md", help="Sources manifest file")
    ap.add_argument("--external-base", default="external_repos", help="Must be in path to allow external linking")
    ap.add_argument("--dry-run", action="store_true", help="Print output instead of writing to file")
    args = ap.parse_args()

    root = repo_root_from_cwd()
    local_skills = root / ".ai" / "SKILLS"
    sources_md = root / args.sources
    external_roots = parse_external_roots(sources_md, root, args.external_base)

    output_content = (
        "# ACTIVE_SKILLSET v0.1 (GENERATED SAMPLE)\n"
        "skillset_id: SKILLSET:ACTIVE:GENERATED\n"
        "source_priority:\n- local\n- external\n\n"
        f"local_skill_root: {local_skills.as_posix()}\n"
        "external_skill_roots:\n" +
        "".join([f"- {p.relative_to(root).as_posix()}\n" for p in external_roots]) +
        "\nnotes:\n- Sample generator output.\n"
        "- Do not edit this file manually. See active_skillset.md for manual edits.\n"
    )

    if args.dry_run:
        print("[DRY-RUN] Output Content:\n" + "-"*40)
        print(output_content)
        print("-" * 40)
    else:
        out = root / args.emit
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(output_content, encoding="utf-8")
        print(f"[OK] wrote: {out}")
        
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
